# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

variables:
  ACR_NAME: theshopreistry               # Replace with your actual ACR name (no ".azurecr.io")
  IMAGE_NAME: theshop-app
  TAG: $(Build.BuildId)
  CONTAINER_APP_NAME: theshop-app-container   # Replace with your Container App name
  RESOURCE_GROUP: TheShop        # Replace with your Azure resource group

steps:
- checkout: self

- script: ./gradlew build
  displayName: 'Build Spring Boot App'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'DockerRegistryServiceConnection'
    repository: $(IMAGE_NAME)
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(TAG)

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    containerRegistry: 'DockerRegistryServiceConnection'
    repository: $(IMAGE_NAME)
    command: 'push'
    tags: |
      $(TAG)

- task: AzureCLI@2
  displayName: 'Deploy to Azure Container Apps'
  inputs:
    azureSubscription: 'AzureServiceConnection'   # Use the name of your service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az config set extension.use_dynamic_install=yes_without_prompt
      az containerapp update \
        --name $(CONTAINER_APP_NAME) \
        --resource-group $(RESOURCE_GROUP) \
        --image $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG)

