version: '3.8'

services:

  # Spring Boot Application
  app:
    image: theshop-app                    # This is the image you built from your Dockerfile
    container_name: theshop-app-container
    ports:
      - "8080:8080"                       # Expose Spring Boot app on port 8080
    networks:
      - theshop-network

networks:
  theshop-network:
    driver: bridge
